language: c

branches:
  only:
    - master
matrix:
  fast_finish: true
  include:
    - os: linux
      env:
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF
    - os: linux
      env:
        - MATRIX_EVAL="CC='gcc -m32'" CF="-DBUILD_SHARED_LIBS=OFF -DCMAKE_LIBRARY_PATH=/usr/lib32" PACKAGES="gcc-multilib lib32z1-dev"
    - os: osx
      env:
        - MATRIX_EVAL="CC=gcc" CF=-DBUILD_SHARED_LIBS=OFF
    - os: osx
      env:
        - MATRIX_EVAL="CC='gcc -m32'" CF=-DBUILD_SHARED_LIBS=OFF
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
  - git clone https://github.com/huskyproject/huskylib ~/build/huskyproject/huskylib
  - git clone https://github.com/huskyproject/smapi ~/build/huskyproject/smapi
  - git clone https://github.com/huskyproject/fidoconf ~/build/huskyproject/fidoconf
  - git clone https://github.com/huskyproject/hptzip ~/build/huskyproject/hptzip
  - git clone https://github.com/huskyproject/areafix ~/build/huskyproject/areafix
  - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
  - sudo ln -s /usr/include/x86_64-linux-gnu/zconf.h /usr/include
script:
  - eval "${MATRIX_EVAL}"
  - cd  ~/build/huskyproject/huskylib
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/smapi
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/fidoconf
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - cd  ~/build/huskyproject/areafix
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - sudo make install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd  ~/build/huskyproject/hptzip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cd build; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake .. ${CF}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake --build .; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo make install; fi
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake .. ${CF}
  - cmake --build .
  - cpack
